<a href="https://youtu.be/A2euuevpYis" target="_parent"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/71px-YouTube_full-color_icon_%282017%29.svg.png" alt="Open In Colab"/></a>


# **Práctico Sistemas Recomendadores: pyreclab - Slope One**

En este práctico seguiremos utilizando [pyreclab](https://github.com/gasevi/pyreclab), con el cual estamos aprendiendo distintas técnicas de recomendación. Seguiremos usando la misma base de datos de los prácticos anteriores, para que puedan comparar los métodos y sus implementaciones. Este práctico está acompañado de un [video comentando la actividad](https://youtu.be/A2euuevpYis).

En esta oportunidad exploraremos el recomendador de Pendiente Uno o **Slope One** [1].

**Adaptado y preparado por:** Francisca Cattan 📩 fpcattan@uc.cl

Referencias 📖
------
[1] *Lemire, D., & Maclachlan, A. (2005, April). Slope One Predictors for Online Rating-Based Collaborative Filtering. In SDM (Vol. 5, pp. 1-5).*


**Nombre**:  Christian Carstens Núñez

## Actividad 1 👓

Antes de empezar con el práctico, responde la siguiente pregunta con lo visto en clases.

**Pregunta:** Explique cómo funciona Slope One (como modelo teórico, no piense en la implementación). En particular explique:

- Repasemos: ¿Por qué este recomendador es un algoritmo de Filtrado Colaborativo?
- Este Filtrado Colaborativo, ¿está basado en el usuario o en los items? ¿Por qué?
- ¿Qué datos recibe Slope One y qué hace con ellos? (qué tipo de columnas y qué calculo)
- ¿Qué pasaría si se agrega un nuevo rating a la base de datos?
- Opcional: ¿Cómo crees que le iría al recomendador con un usuario que acaba de entrar al sistema y ha asignado muy pocos ratings?

💡 *Hint: La bibliografía todo lo puede.*

**Respuesta:**

Slop One es un algoritmo de filtrado colaborativo gracias a que las recomendaciones son generadas con el feedback de múltiples usuarios, y a partir de todos estos grnrts uns recomendación.

Por otro lado, es basado en ítems, pues genera recomendaciones en base a los ratings recibidos por distintos ítems. Particularmente, analiza las diferenciasde ratings evaluadas por usuarios a distintos ítems, y a partir de esto genera una ecuación lineal de pendiente uno con el fin de predecir el rating de un ítem.

Como se mencionó en el punto anterior, este algoritmo necesita tener feedback, particularmente ratings, de usuarios a ítems. A partir de esto, se genera una matriz usuario-ítem, donde los valores están dados por los ratings que el usuario i entrega al ítem j. Por ende, una fila corresponedrá a los ratings que ha entregado un usuario a distintos ítems, y una columna a los ratings recibidos por un ítem provenientes de distintos usuarios. A partir de esto, se predice el rating otorgado por un usuario a un ítem a partir de de una ecuación lineal de las diferencias entre calificaciones del usuario al resto de los ítems, con respecto al ítem i.

Una característica de este algoritmo es que es memory-based, gastanto bajos tiempos de cómputo. Si se agrega un nuevo rating, se debe calcular nuevamente la predicción, lo cual tiene un costo bajo, pues solo considera los ítems evaluados por el active user.

Este método es muy propenso al cold start, por lo que no tendría un buen desempeño.


# **Configuración Inicial**

## Paso 1:
Descargue directamente a Colab los archivos del dataset ejecutando las siguientes 3 celdas:


In [1]:
!curl -L -o "u1.base" "https://drive.google.com/uc?export=download&id=1bGweNw7NbOHoJz11v6ld7ymLR8MLvBsA"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0   1480      0 --:--:-- --:--:-- --:--:--  1480
100 1546k  100 1546k    0     0  3867k      0 --:--:-- --:--:-- --:--:-- 3867k


In [2]:
!curl -L -o "u1.test" "https://drive.google.com/uc?export=download&id=1f_HwJWC_1HFzgAjKAWKwkuxgjkhkXrVg"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0    917      0 --:--:-- --:--:-- --:--:--   917
100  385k  100  385k    0     0   686k      0 --:--:-- --:--:-- --:--:--  686k


In [3]:
!curl -L -o "u.item" "https://drive.google.com/uc?export=download&id=10YLhxkO2-M_flQtyo9OYV4nT9IvSESuz"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0   2535      0 --:--:-- --:--:-- --:--:--  2535
100  230k  100  230k    0     0   787k      0 --:--:-- --:--:-- --:--:--  787k


Los archivos **u1.base** y **u1.test** tienen tuplas {usuario, item, rating, timestamp}, que es la información de preferencias de usuarios sobre películas en una muestra del dataset [movielens](https://grouplens.org/datasets/movielens/).

## Paso 2:

Instalamos pyreclab utilizando pip.

In [4]:
!pip install pyreclab --upgrade

     |████████████████████████████████| 234 kB 1.6 MB/s 


## Paso 3:

Hacemos los imports necesarios para este práctico.

In [5]:
import pyreclab
import numpy as np
import pandas as pd

# **El dataset**

💡 *En prácticos anteriores, vimos como analizar este dataset. Puedes revisarlos en caso de dudas.*

## Paso 4:

Ya que queremos crear una lista de recomendación de items para un usuario en especifico, necesitamos obtener información adicional de cada película tal como título, fecha de lanzamiento, género, etc. Cargaremos el archivo de items descargado "u.item" para poder mapear cada identificador de ítem al conjunto de datos que lo describe.

In [6]:
# Definimos el orden de las columnas
info_cols = [ 'movieid', 'title', 'release_date', 'video_release_date', 'IMDb_URL', \
              'unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy', \
              'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', \
              'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western' ]

# Asignamos a una variable la estructura de datos de los items
info_file = pd.read_csv('u.item', sep='|', index_col = 0, names = info_cols, header=None, encoding='latin-1')

# **Slope One**

## Paso 5:

Seguiremos un camino muy similar a los ejercicios de User KNN e Item KNN. Crearemos una instancia del algoritmo de recomendación y luego pasaremos a la fase de entrenamiento.

In [7]:
# Declaramos la instancia SlopeOne
mySlopeOne = pyreclab.SlopeOne(dataset='u1.base', dlmchar=b'\t', header=False, usercol=0, itemcol=1, ratingcol=2)

In [8]:
# Y enntrenamos
mySlopeOne.train()

## Actividad 2 👓

**Pregunta:** Explique qué hace el método `train()` en este caso, dado el modelo teórico. ¿Calcula información?, ¿no hace nada?, ¿ordena los datos? 

**Respuesta:**
Al entrenar, se deberían realizar los cálculos de Slope One. 
Es decir, para cada usuario se calculan las diferencias de ratings entre el ítem buscado y el resto, y se computa la ecuación lineal. Estos resultados quedan almacenados en memoria.



## Paso 6:

Llego la hora de predecir el rating.

In [9]:
# Esta es la predicción de rating que el usuario ID:457 otorgaría al ítem ID:37
# De esta forma podemos comparar el resultado con los prácticos anteriores
mySlopeOne.predict("457", "37")

3.2408759593963623

In [10]:
# También podemos guardar la predicción en una variable
prediction = mySlopeOne.predict("457", "37")

In [11]:
# Podemos comprobar las peliculas rankeadas por el usuario ID:457
# Que ciertamente ha participado activamente (¡156 items!)
train_file = pd.read_csv('u1.base', sep='\t', names = ['userid', 'itemid', 'rating', 'timestamp'], header=None)
train_file[train_file['userid'] == 457]

userid  itemid  rating  timestamp
37269     457       1       4  882393244
37270     457       7       4  882393278
37271     457       9       5  882393485
37272     457      11       4  882397020
37273     457      13       3  882393883
...       ...     ...     ...        ...
37420     457    1047       2  882395964
37421     457    1119       4  882398308
37422     457    1168       5  882548761
37423     457    1210       4  882549905
37424     457    1221       4  882549438

[156 rows x 4 columns]

In [12]:
# Y también cuáles usuarios han rankeado la pelicula ID:37
train_file[train_file['itemid'] == 37]

userid  itemid  rating  timestamp
1302       13      37       1  882397011
14851     201      37       2  884114635
19670     268      37       3  876514002
29489     363      37       2  891498510
31084     385      37       4  880013483
32996     405      37       1  885548384
62777     773      37       3  888540352

## Actividad 3 👓

Haremos un pequeño experimento para entender mejor como funciona Slope One. Gracias al ejercicio anterior, sabemos que el usuario 457 ya ha asignado el mejor rating (5 ⭐) a las dos peliculas ID:9 e ID:1168. Comparemos.

**Pregunta:** ¿Cómo se explican estos resultados?  

**Respuesta:** Se puede ver una tendencia del usuario a otorgar valores más céntricos y no extremos (como 5). El ítem 9 tiene más altas diferencias de ratings, por lo que hay una mayor variación que en el caso de la 1168, respecto a los ítems vistos por el ususario. 


In [13]:
prediction_id9 = mySlopeOne.predict("457", "9")
prediction_id1168 = mySlopeOne.predict("457", "1168")

print('Prediction for ID:9 :', prediction_id9)
print('Prediction for ID:1168 :', prediction_id1168)

Prediction for ID:9 : 4.530702114105225
Prediction for ID:1168 : 4.166153907775879


## Paso 7:

Generaremos ahora una lista ordenada de las top-N recomendaciones, dado un usuario.



In [14]:
# Mediante el método recommend() genereremos una lista top-5 recomendaciones para el usuario ID:457
reclist_slopeone = mySlopeOne.recommend("457", 5)

# Y visualizaremos el resultado
print('Lista de items según ID:', reclist_slopeone)

Lista de items según ID: ['1592', '1589', '1656', '1431', '1653']


In [15]:
# Lo convertimos a numpy array
recmovies_slopeone = np.array(reclist_slopeone).astype(int)

# Utilizamos la estructura de datos de los items para encontrar los títulos recomendados
print('Lista de items por nombre:')
info_file.loc[recmovies_slopeone]['title']

Lista de items por nombre:


movieid
1592                               Magic Hour, The (1998)
1589                                   Schizopolis (1996)
1656                                   Little City (1998)
1431                                  Legal Deceit (1997)
1653    Entertaining Angels: The Dorothy Day Story (1996)
Name: title, dtype: object

## Actividad 4 👩🏻‍💻

Genera una nueva recomendacion, modificando los hiperparametros de usuario y topN a tu elección.

**Pregunta:** ¿Ves una diferencia en la recomendación entre el nuevo usuario y el usuario ID:457?

**Respuesta:** Si bien coinciden algunas películas, se evidencia que es una recomendación personalizada.

In [16]:
# Escribe el nuevo codigo aqui

# Mediante el método recommend() genereremos una lista top-5 recomendaciones para el usuario ID:457
reclist_slopeone = mySlopeOne.recommend("1", 10)

# Y visualizaremos el resultado
print('Lista de items según ID:', reclist_slopeone)

# Lo convertimos a numpy array
recmovies_slopeone = np.array(reclist_slopeone).astype(int)

# Utilizamos la estructura de datos de los items para encontrar los títulos recomendados
print('Lista de items por nombre:')
info_file.loc[recmovies_slopeone]['title']

Lista de items según ID: ['1656', '1653', '1064', '1651', '1650', '1645', '1643', '1642', '1636', '1585']
Lista de items por nombre:


movieid
1656                                   Little City (1998)
1653    Entertaining Angels: The Dorothy Day Story (1996)
1064                                     Crossfire (1947)
1651                         Spanish Prisoner, The (1997)
1650                              Butcher Boy, The (1998)
1645                              Butcher Boy, The (1998)
1643                                    Angel Baby (1995)
1642                             Some Mother's Son (1996)
1636                           Brothers in Trouble (1995)
1585                                American Dream (1990)
Name: title, dtype: object

## Actividad 5 👩🏻‍💻

Dado el usuario ID:44, cree dos listas de películas recomendadas; la primera utilizando el algoritmo Most Popular y la segunda utilizando el algoritmo Slope One.

**Pregunta:** Realice un analisis apreciativo de las similitudes y diferencias entre ambas recomendaciones.

**Respuesta:**

In [17]:
# Escribe el nuevo codigo aqui

mp = pyreclab.MostPopular(dataset='u1.base',
                   dlmchar=b'\t',
                   header=False,
                   usercol=0,
                   itemcol=1,
                   ratingcol=2)
mp.train()

In [20]:

reclist_mp = mp.recommend("44", 5)
recmovies_mp = np.array(reclist_mp).astype(int)

print('Lista de items por nombre:')
info_file.loc[recmovies_mp]

Lista de items por nombre:


title release_date  ...  War Western
movieid                                            ...             
50                  Star Wars (1977)  01-Jan-1977  ...    1       0
100                     Fargo (1996)  14-Feb-1997  ...    0       0
181        Return of the Jedi (1983)  14-Mar-1997  ...    1       0
286      English Patient, The (1996)  15-Nov-1996  ...    1       0
1                   Toy Story (1995)  01-Jan-1995  ...    0       0

[5 rows x 23 columns]

In [21]:
reclist_slopeone = mySlopeOne.recommend("44", 5)
recmovies_slopeone = np.array(reclist_slopeone).astype(int)

print('Lista de items por nombre:')
info_file.loc[recmovies_slopeone]

Lista de items por nombre:


title release_date  ...  War Western
movieid                                         ...             
1656           Little City (1998)  20-Feb-1998  ...    0       0
1064             Crossfire (1947)  01-Jan-1947  ...    0       0
1643            Angel Baby (1995)  10-Jan-1997  ...    0       0
1642     Some Mother's Son (1996)  27-Dec-1996  ...    0       0
1625            Nightwatch (1997)  22-Apr-1997  ...    0       0

[5 rows x 23 columns]

Se evidencia que las recomendaciones son totalmente distintas, incluidos los rasgos de las mismas.